image:
  repository: thelounge/thelounge
  pullPolicy: IfNotPresent
  tag: 4.4.3@sha256:cf964cafc690350e6d6d30c719d8d3ad9c12d52c87ab48e93d2589c0dbd272b2
service:
  main:
    ports:
      main:
        port: 10061
        targetPort: 9000
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            THELOUNGE_HOME: "/config"
