name: "Apps: Test Push"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ixsystems/catalog_validation:latest@sha256:ec054455af9857782d13f0507b0e0378ed0dee83dab11a3e1e5939eebb083522

    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
        name: Checkout

      - name: Validate catalog format
        run: |
          /bin/bash -c "PWD=${pwd}; /usr/local/bin/catalog_validate validate --path $PWD"
