image:
  pullPolicy: IfNotPresent
  repository: ich777/rapidphotodownloader
  tag: latest@sha256:1d572e12e3c6e1cccf73ed17dfaa75b3efb65e21dca088683bea15aee08870da
persistence:
  datadir:
    enabled: true
    mountPath: /rapidphotodownloader
  destinantionfolder:
    enabled: true
    mountPath: /media/destination
  sourcefolder:
    enabled: true
    mountPath: /media/source
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8080
        protocol: tcp
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CUSTOM_RES_H: "881"
            CUSTOM_RES_W: "1024"
            DL_URL: https://launchpad.net/rapid/pyqt/0.9.17/+download/install.py
            FORCE_UPDATE: ""
