image:
  repository: traccar/traccar
  tag: 6.5@sha256:e569632fe9d6dfef3152e8602992508cfe5bc3ea2f24ae4220e8445af3679a60
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8082
        targetPort: 8082
persistence:
  data:
    enabled: true
    mountPath: "/opt/traccar/data"
cnpg:
  main:
    enabled: true
    user: traccar
    database: traccar
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CONFIG_USE_ENVIRONMENT_VARIABLES: true
            LOGGER_CONSOLE: true
            DATABASE_DRIVER: "org.postgresql.Driver"
            DATABASE_USER: "{{ .Values.cnpg.main.user }}"
            DATABASE_PASSWORD:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: jdbc
