image:
  pullPolicy: IfNotPresent
  repository: xavierh/goaccess-for-nginxproxymanager
  tag: latest@sha256:ced21d530071a5fac9542571afd30fdb502df3084e42abaf93078ade210c2042
persistence:
  hostpath1:
    enabled: true
    mountPath: /opt/log
    readOnly: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 7880
        protocol: tcp
        targetPort: 7880
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BASIC_AUTH: "True"
            BASIC_AUTH_PASSWORD: x
            BASIC_AUTH_USERNAME: x
            DEBUG: "False"
            EXCLUDE_IPS: ""
            SKIP_ARCHIVED_LOGS: "False"
