image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: daysofwar@sha256:fadb1daeffc058d1fb0883661aa55adef7941282f89be8969cb49c7722c405b4
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 7777
        protocol: udp
        targetPort: 7777
  steamport:
    enabled: true
    ports:
      steamport:
        enabled: true
        port: 27015
        protocol: udp
        targetPort: 27015
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "541790"
            GAME_PARAMS: dow_cathedral
            GAME_PORT: "7777"
            PASSWRD: ""
            QUERY_PORT: "27015"
            USERNAME: ""
            VALIDATE: "false"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
