image:
  repository: ghcr.io/onedr0p/theme-park
  pullPolicy: IfNotPresent
  tag: 1.18@sha256:210d8f5d9466df493503184fb076bbf1fb9fbc2b42e273cd4516ac3fd1df7ba2
service:
  main:
    ports:
      main:
        port: 10244
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
