image:
  repository: ich777/steamcmd
  tag: unturned@sha256:180f269a16fc70c44c3646d240f3b52907d86ff182462f65d86189410d58b70a
  pullPolicy: IfNotPresent

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        protocol: udp
        port: 27015
  steam:
    enabled: true
    ports:
      steam:
        enabled: true
        protocol: tcp
        port: 27016

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            GAME_PORT: "{{ .Values.service.main.ports.main.port }}"
            GAME_ID: "1110390"
            USERNAME: ""
            PASSWRD: ""
            ROCKET_FORCE_UPDATE: ""
            ROCKET_MOD: ""
            ROCKET_URL: https://ci.rocketmod.net/job/Rocket.Unturned/lastSuccessfulBuild/artifact/Rocket.Unturned/bin/Release/Rocket.zip
            VALIDATE: false

persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd

portal:
  open:
    enabled: false
