image:
  pullPolicy: IfNotPresent
  repository: jasongdove/ersatztv
  tag: v0.8.8@sha256:a183c6f1ee92a0c348bccbb456d829b754cd642f0b578b90f31bacd9c7b1d325
imageSelector: image
nvidiaImage:
  pullPolicy: Always
  repository: jasongdove/ersatztv
  tag: v0.8.8-nvidia@sha256:673edfdd31ae906c4d473205b7ce041531c2417e07bd6ea168272e47b5c3e345
persistence:
  config:
    enabled: true
    mountPath: /root/.local/share/ersatztv
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10607
        protocol: http
        targetPort: 8409
vaapiImage:
  pullPolicy: Always
  repository: jasongdove/ersatztv
  tag: v0.8.8-vaapi@sha256:2da0a908cb7f7ab9133fe81bba2d343c585e5837d5513a7afb6d00734257ca25
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: http
