image:
  repository: linuxserver/snapdrop
  tag: latest@sha256:e87bdcae338b2a2df8fcc12a3ddfd73c8e7ca110d6605d31ee332a8ae320d55f
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10215
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
