image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: stationeers@sha256:06e3d496bfe033c1f2aef237d25111648986c4674b45799058b535ba2e926930
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  gameport:
    enabled: true
    ports:
      gameport:
        enabled: true
        port: 27500
        protocol: udp
        targetPort: 27500
  main:
    ports:
      main:
        port: 27015
        protocol: udp
        targetPort: 27015
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "600760"
            GAME_PARAMS: AutoSave true SaveInterval 300
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
