image:
  repository: ghcr.io/linuxserver/doublecommander
  pullPolicy: IfNotPresent
  tag: latest@sha256:eba92db022453647da92ae5c1bf2d8e0c5e8dd53fd5175f27ff8e7bfc078dd13
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10034
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          securityContext:
            capabilities:
              add:
                - SYS_CHROOT
                - KILL
                - NET_BIND_SERVICE
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
