---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-weave-gitops
  namespace: flux-system
spec:
  path: ./cluster/main/weave-gitops/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: operators-prometheus-operator
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
