project_name: clustertool
builds:
  - id: clustertool
    dir: clustertool
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/truecharts/private/clustertool/cmd.version={{.Version}}  # Adjust path if necessary
archives:
  - name_template: "{{.ProjectName}}_{{ .Version }}_{{.Os}}_{{.Arch}}"
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge pull request #\d+ from'
      - "^docs"
      - "^test"
    include:
      - "clustertool"
release:
  github:
    owner: truecharts
    name: clustertool-public
  draft: true
  make_latest: false

before:
  hooks:
    - chmod +x ./clustertool/partial_builds/partial_build.sh
    - ./clustertool/partial_builds/partial_build.sh
    - chmod +x ./clustertool/embed/download_talosctl.sh
    - ./clustertool/embed/download_talosctl.sh
    - find
