image:
  repository: whyour/qinglong
  pullPolicy: IfNotPresent
  tag: 2.17.11@sha256:4356d28c5daef267f5db5ed6a5f913fbcf1724cc28fda5deaa96525e87031e39
service:
  main:
    ports:
      main:
        targetPort: 5700
        port: 10176
persistence:
  data:
    enabled: true
    mountPath: "/ql/data"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
