image:
  repository: privoce/vocechat-server
  pullPolicy: IfNotPresent
  tag: v0.3.57@sha256:45daa3e9cb2716bd86463fac3b5224449169e892423258eb1dac0f8328d71388

service:
  main:
    ports:
      main:
        protocol: http
        port: 3009

vocechat:
  frontend_url: localhost:3009

workload:
  main:
    podSpec:
      containers:
        main:
          args:
            - --network.bind
            - 0.0.0.0:{{ .Values.service.main.ports.main.port }}
            - --network.frontend_url
            - "{{ .Values.vocechat.frontend_url }}"

persistence:
  data:
    enabled: true
    mountPath: "/home/vocechat-server/data"

portal:
  open:
    enabled: true
