image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: postscriptum@sha256:03d7d788ca29372778d8e5876c868d068f638c96abb2e5324ceadc6e678568a1
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10027
        protocol: udp
        targetPort: 10027
  queryport:
    enabled: true
    ports:
      queryport:
        enabled: true
        port: 10037
        protocol: udp
        targetPort: 10037
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATA_PERM: "770"
            GAME_ID: "746200"
            GAME_PARAMS: Port=10027 QueryPort=10037 -log
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
