image:
  repository: metabase/metabase
  pullPolicy: IfNotPresent
  tag: v0.50.30@sha256:abdcb52b5b9ab061097fa4b4cfbdb13b39ed19125e6701cd1dbc391069e140c2
service:
  main:
    ports:
      main:
        protocol: http
        port: 13030
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            MB_JETTY_PORT: "{{ .Values.service.main.ports.main.port }}"
            JAVA_TIMEZONE: "{{ .Values.TZ }}"
            MB_DB_TYPE: "postgres"
            MB_DB_USER: "{{ .Values.cnpg.main.user }}"
            MB_DB_DBNAME: "{{ .Values.cnpg.main.database }}"
            MB_DB_PORT: 5432
            MB_DB_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
            MB_DB_PASS:
              secretKeyRef:
                name: cnpg-main-user
                key: password
persistence:
  plugins:
    enabled: true
    mountPath: "/plugins"
# Enabled postgres
cnpg:
  main:
    enabled: true
    user: metabase
    database: metabase
portal:
  open:
    enabled: true
