image:
  repository: photoprism/photoprism
  tag: 240915@sha256:1f14335e2cd9dfaadc555ac8d40aa8a3966a5b5e5ef88fa78973ef7e8673fa2b
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 2342
        targetPort: 2342
persistence:
  storage:
    enabled: true
    mountPath: "/assets"
  photoprismtemp:
    enabled: true
    mountPath: "/photoprism_temp"
    type: emptyDir
  originals:
    enabled: true
    mountPath: "/photoprism/originals"
  import:
    enabled: true
    mountPath: "/photoprism/import"
mariadb:
  enabled: true
  mariadbUsername: photoprism
  mariadbDatabase: photoprism
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOME: "/photoprism"
            PHOTOPRISM_ORIGINALS_PATH: "/photoprism/originals"
            PHOTOPRISM_IMPORT_PATH: "/photoprism/import"
            PHOTOPRISM_TEMP_PATH: "/photoprism_temp"
            PHOTOPRISM_STORAGE_PATH: "/assets/storage"
            PHOTOPRISM_SIDECAR_PATH: "/assets/sidecar"
            PHOTOPRISM_CACHE_PATH: "/assets/cache"
            PHOTOPRISM_CONFIG_PATH: "/assets/config"
            PROTOPRISM_BACKUP_PATH: "/assets/backup"
            PHOTOPRISM_PUBLIC: false
            PHOTOPRISM_UID: "{{ .Values.securityContext.container.runAsUser }}"
            PHOTOPRISM_GID: "{{ .Values.securityContext.container.runAsGroup }}"
            PHOTOPRISM_UMASK: "{{ .Values.securityContext.container.UMASK }}"
            PHOTOPRISM_DATABASE_DRIVER: "mysql"
            PHOTOPRISM_DATABASE_NAME: "photoprism"
            PHOTOPRISM_DATABASE_USER: "photoprism"
            PHOTOPRISM_DATABASE_SERVER:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: plainporthost
            PHOTOPRISM_DATABASE_PASSWORD:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: mariadb-password
            PHOTOPRISM_ADMIN_PASSWORD: "please-change"
