image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: barotrauma@sha256:7e04c88d0aeae1a482f1b027598301fcbd9fe8c01dcc65f942b4619e7183cd2c
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 27015
        protocol: udp
        targetPort: 27015
  steamqueryport:
    enabled: true
    ports:
      steamqueryport:
        enabled: true
        port: 27016
        protocol: udp
        targetPort: 27016
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "1026340"
            GAME_PARAMS: ""
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
