image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: dayz@sha256:46cb5778ab2c99ffe3c7e70f3e5e232ddd2374c7ea2354fe83c97229c3a8783a
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 2302
        protocol: udp
        targetPort: 2302
  steamqueryport:
    enabled: true
    ports:
      steamqueryport:
        enabled: true
        port: 27016
        protocol: udp
        targetPort: 27016
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "1042420"
            GAME_PARAMS: ""
            GAME_PORT: "2302"
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
