image:
  repository: jlesage/avidemux
  tag: v24.09.1@sha256:820f3f22f0710c739747de5fc30686d232c005a66cd6a7a6d6245c04fa3c72f0
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10272
        protocol: http
        targetPort: 5800
  vnc:
    enabled: true
    ports:
      vnc:
        enabled: true
        port: 10273
        protocol: tcp
        targetPort: 5900
avidemux:
  KEEP_APP_RUNNING: false
  DISPLAY_WIDTH: 1280
  DISPLAY_HEIGHT: 768
  SECURE_CONNECTION: false
  ENABLE_CJK_FONT: false
configmap:
  avidemux:
    enabled: true
    data:
      ENABLE_CJK_FONT: '{{ ternary "1" "0" .Values.avidemux.ENABLE_CJK_FONT }}'
      KEEP_APP_RUNNING: '{{ ternary "1" "0" .Values.avidemux.KEEP_APP_RUNNING }}'
      SECURE_CONNECTION: '{{ ternary "1" "0" .Values.avidemux.SECURE_CONNECTION }}'
      DISPLAY_WIDTH: "{{ .Values.avidemux.DISPLAY_WIDTH }}"
      DISPLAY_HEIGHT: "{{ .Values.avidemux.DISPLAY_HEIGHT }}"
workload:
  main:
    podSpec:
      containers:
        main:
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
                - KILL
          envFrom:
            - configMapRef:
                name: "avidemux"
          env:
            VNC_PASSWORD: ""
persistence:
  config:
    enabled: true
    mountPath: /config
  storage:
    enabled: true
    mountPath: /storage
portal:
  open:
    enabled: true
