---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: cert-manager
patchesJson6902:
  - path: jsonpatch.yaml
    target:
      kind: Deployment
      name: cert-manager
