image:
  pullPolicy: IfNotPresent
  repository: binhex/arch-hexchat
  tag: latest@sha256:9300f7443579f05739c43ade4da0e347d45d9e0f3c85087a832e92875ee6196f
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10307
        protocol: http
        targetPort: 6080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            VNC_PASSWORD: ""
            WEBPAGE_TITLE: HexChat
