image:
  repository: ghcr.io/linuxserver/grav
  pullPolicy: IfNotPresent
  tag: 1.7.46@sha256:620e8a61285e3537d1403ff935af448dac33c2d8a6649723af005bc0fb8ca325
service:
  main:
    ports:
      main:
        port: 10012
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
