---
name: "Metadata: Label Commenter"

on:
  workflow_dispatch:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - labeled
      - unlabeled

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    name: Label commenter
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          ref: master

      - uses: peaceiris/actions-label-commenter@f0dbbef043eb1b150b566db36b0bdc8b7f505579 # v1
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
