image:
  repository: ghcr.io/linuxserver/medusa
  pullPolicy: IfNotPresent
  tag: 1.0.21@sha256:5ed3b059b125795eab93deb704dda5380c92796c9f1cd1aa39971e57c5751698
service:
  main:
    ports:
      main:
        port: 10068
        targetPort: 8081
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
