---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  VIP: 192.168.10.100
  MASTER1IP: 192.168.10.110
  GATEWAY: 192.168.10.1
  METALLB_RANGE: 192.168.10.100-192.168.10.250
  KUBEAPPS_IP: 192.168.10.105
  EMAIL: "TBD"
  CLOUDFLARE_TOKEN: "TBD"
  GITHUB_TOKEN: "TBD"
  GITHUB_USER: "TBD"
  GITHUB_REPOSITORY: "TBD"
  BASE_DOMAIN: "TBD"
