image:
  pullPolicy: IfNotPresent
  repository: accetto/ubuntu-vnc-xfce-blender-g3
  tag: latest@sha256:8f31db71f9c5cfc474652f22fc6dc88f5a9f0c7fa86c6050183fd91910455a78
persistence:
  internalshare:
    enabled: true
    mountPath: /UNRAID_SHARE
  storageprojects:
    enabled: true
    mountPath: /srv/projects
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 6901
        protocol: http
        targetPort: 6901
  webuivnc:
    enabled: true
    ports:
      webuivnc:
        enabled: true
        port: 5901
        protocol: tcp
        targetPort: 5901
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            VNC_PW: unraid
            VNC_RESOLUTION: 1360x768
