image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: corekeeper@sha256:667aedea4063e4a12f911c00851da341f4d65ed8b9da05047a5827635b26df43
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "1963720"
            GAME_PARAMS: ""
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
            WORLD_INDEX: "0"
            WORLD_NAME: Core Keeper Docker
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
