image:
  pullPolicy: IfNotPresent
  repository: x1unix/go-playground
  tag: latest@sha256:004f5843eb5e1766fa114f25427a20ab52debb963215a731fc855c9039026631
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8888
        protocol: tcp
        targetPort: 8000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            APP_CLEAN_INTERVAL: 10m
            APP_DEBUG: "false"
