image:
  repository: ghcr.io/linuxserver/boinc
  pullPolicy: IfNotPresent
  tag: latest@sha256:d75e5d40e6334325beb1022fc9c37ca790a660d1699eb2a2d7258b77e66f71ff
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 8080
        protocol: http
        port: 10142
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PASSWORD: ""
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
