image:
  repository: ghcr.io/ajnart/homarr
  tag: 0.15.4@sha256:c13f04c95fdfbdb710375301cc45783a4c239eaedc96258e2a026feead213f99
  pullPolicy: IfNotPresent
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NEXTAUTH_SECRET:
              secretKeyRef:
                name: homarr-secrets
                key: NEXTAUTH_SECRET
service:
  main:
    ports:
      main:
        port: 10245
        targetPort: 7575
persistence:
  config:
    enabled: true
    mountPath: "/app/data/configs"
  icons:
    enabled: true
    mountPath: "/app/public/icons"
  data:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: true
