image:
  pullPolicy: IfNotPresent
  repository: ich777/vintagestory
  tag: latest@sha256:89243f1128df1463c2ce5f43a1e40f0910a6fba35704111809b0587577347378
persistence:
  serverfiles:
    enabled: true
    mountPath: /vintagestory
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 42420
        protocol: tcp
        targetPort: 42420
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_PARAMS: ""
            VS_CHANNEL: stable@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
