image:
  pullPolicy: IfNotPresent
  repository: songkong/songkong
  tag: latest@sha256:bae97bb8a91fdf8065e4c7481df15b51cad7ed98b891b1f358192b3ce42752e2
persistence:
  music:
    enabled: true
    mountPath: /music
  songkongconfig:
    enabled: true
    mountPath: /songkong
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 4567
        protocol: tcp
        targetPort: 4567
