image:
  repository: jorenn92/maintainerr
  pullPolicy: IfNotPresent
  tag: 2.1.2@sha256:afca11e4a134211b8ff49047e43ed34f887f7f3bd176be0ec475e7d141589384

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 6246
        port: 6246

persistence:
  data:
    enabled: true
    mountPath: "/opt/data"

portal:
  open:
    enabled: true
