image:
  pullPolicy: IfNotPresent
  repository: accetto/ubuntu-vnc-xfce-freecad-g3
  tag: latest@sha256:f9e530ebf6fa12091f956a4b4dee16919a0d0b6fbd30d74aac3352dab8affb87
persistence:
  internalshare:
    enabled: true
    mountPath: /UNRAID_SHARE
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 6901
        protocol: http
        targetPort: 6901
  webuivnc:
    enabled: true
    ports:
      webuivnc:
        enabled: true
        port: 5901
        protocol: tcp
        targetPort: 5901
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            VNC_PW: unraid
            VNC_RESOLUTION: 1360x768
