image:
  pullPolicy: IfNotPresent
  repository: mikenye/tar1090
  tag: latest@sha256:0851fa02edd008c7d6b5258b1a81b2e2653b569cdbdb14cef9ee3b03639e17a7
persistence: {}
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8078
        protocol: tcp
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BEASTHOST: <BEASTHOST>
            LAT: xx.xxxxx
            LONG: xx.xxxxx
            MLATHOST: <MLATHOST>
