image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: l4d@sha256:24980274cc8cd816355aae31df0e5083e5ec7389d6f14d37d955f044882926bd
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 27015
        protocol: udp
        targetPort: 27015
  tcprcon:
    enabled: true
    ports:
      tcprcon:
        enabled: true
        port: 27015
        protocol: tcp
        targetPort: 27015
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "222840"
            GAME_NAME: left4dead
            GAME_PARAMS: +maxplayers 4 +map l4d_farm04_barn
            GAME_PORT: "27015"
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
          probes:
            liveness:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
              type: tcp
            readiness:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
              type: tcp
            startup:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
              type: tcp
