image:
  repository: docker.io/nodered/node-red
  pullPolicy: IfNotPresent
  tag: 4.0.5@sha256:7b635f720d9d1aba676925a93fcf20811bbb62b476752b896177faccb28e5ee9
service:
  main:
    ports:
      main:
        port: 1880
        targetPort: 1880
persistence:
  data:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          env: {}
