image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: alienswarmreactivedrop@sha256:72a103648301d035e1a09aa4bd4d59bd67c5ebe259920899e55f82d6c418008a
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 27015
        protocol: udp
        targetPort: 27015
  tcprconport:
    enabled: true
    ports:
      tcprconport:
        enabled: true
        port: 27015
        protocol: tcp
        targetPort: 27015
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "563560"
            GAME_NAME: reactivedrop
            GAME_PARAMS: +map lobby -maxplayers 4 +exec server.cfg
            GAME_PORT: "27015"
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
          probes:
            liveness:
              port: "{{ .Values.service.tcprconport.ports.tcprconport.targetPort }}"
              type: tcp
            readiness:
              port: "{{ .Values.service.tcprconport.ports.tcprconport.targetPort }}"
              type: tcp
            startup:
              port: "{{ .Values.service.tcprconport.ports.tcprconport.targetPort }}"
              type: tcp
