image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: theforest@sha256:40151e7da3f0c0b7959ece9b42c2b5ef262828a6296a3dd9272c5b66fd32d073
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  gameport:
    enabled: true
    ports:
      gameport:
        enabled: true
        port: 27015
        protocol: udp
        targetPort: 27015
  main:
    ports:
      main:
        port: 8766
        protocol: udp
        targetPort: 8766
  steamqueryport:
    enabled: true
    ports:
      steamqueryport:
        enabled: true
        port: 27016
        protocol: udp
        targetPort: 27016
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "556450"
            GAME_PARAMS: ""
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
