service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        port: 8080

workload:
  main:
    enabled: true
    podSpec:
      containers:
        main:
          enabled: true
          args:
            - --port
            - "8080"
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true

networkPolicy:
  main:
    enabled: true

    ingress:
      - from:
          - ipBlock:
              cidr: 172.17.0.0/16
              except:
                - 172.17.1.0/24
          - namespaceSelector:
              matchLabels:
                project: myproject
          - podSelector:
              matchLabels:
                role: frontend
          - namespaceSelector:
              matchLabels:
                project: myproject2
            podSelector:
              matchLabels:
                role: frontend2
        ports:
          - protocol: TCP
            port: 6379
    egress:
      - to:
          - ipBlock:
              cidr: 172.17.2.0/16
              except:
                - 172.17.2.0/24
          - namespaceSelector:
              matchLabels:
                project: myproject3
          - podSelector:
              matchLabels:
                role: frontend3
          - namespaceSelector:
              matchLabels:
                project: myproject4
            podSelector:
              matchLabels:
                role: frontend4
        ports:
          - protocol: TCP
            port: 5978
