service:
  main:
    enabled: true
    primary: true
    ports:
      main:
        enabled: true
        primary: true
        protocol: http
        port: 8080

workload:
  main:
    enabled: true
    primary: true
    type: Deployment
    podSpec:
      containers:
        main:
          enabled: true
          primary: true
          args:
            - --port
            - "8080"
          probes:
            liveness:
              enabled: true
              type: http
              port: "{{ .Values.service.main.ports.main.port }}"
            readiness:
              enabled: true
              type: http
              port: "{{ .Values.service.main.ports.main.port }}"
            startup:
              enabled: true
              type: http
              port: "{{ .Values.service.main.ports.main.port }}"

schedules:
  test:
    enabled: true
    schedule: "0 0 * * *"
  test2:
    enabled: true
    labels:
      myenv: foo
    annotations:
      myenv: foo
    schedule: "0 0 * * *"
    useOwnerReferencesInBackup: false
    template:
      ttl: "240h"
      storageLocation: default
  test3:
    enabled: true
    schedule: "0 0 * * *"
    template:
      ttl: "240h"
      storageLocation: default
      includedNamespaces:
        - foo
