service:
  main:
    enabled: true
    primary: true
    ports:
      main:
        enabled: true
        primary: true
        protocol: http
        port: 8080

workload:
  main:
    enabled: true
    primary: true
    type: Deployment
    podSpec:
      containers:
        main:
          enabled: true
          primary: true
          args:
            - --port
            - "8080"
          probes:
            liveness:
              enabled: true
              type: http
              port: "{{ .Values.service.main.ports.main.port }}"
            readiness:
              enabled: true
              type: http
              port: "{{ .Values.service.main.ports.main.port }}"
            startup:
              enabled: true
              type: http
              port: "{{ .Values.service.main.ports.main.port }}"

# Parameters for the VolumeSnapshotLocation(s). Configure multiple by adding other element(s) to the volumeSnapshotLocation slice.
# See https://velero.io/docs/v1.6/api-types/volumesnapshotlocation/
volumeSnapshotLocation:
  test:
    enabled: true
    # provider is the name for the volume snapshot provider.
    provider: aws
    credential:
      # AWS/s3 credentials to be put into secret (mandatory if provider == aws/s3)
      aws:
        id: fdgsdfghsdfgh
        key: dfgdfhsdfgh
    # Additional provider-specific configuration. See link above
    # for details of required/optional fields for your provider.
    config: {}
