image:
  repository: portainer/portainer-ce
  tag: 2.23.0@sha256:bac59ebb8208d09aa3f1b13f2467b8145cad01c754dc8c59a7d5cf0677d5c963
  pullPolicy: IfNotPresent
beImage:
  repository: portainer/portainer-ee
  tag: 2.23.0@sha256:fea4a02f95ef41b2c07264b56c6309aaedbb720e272302b67d11e066239cb781
  pullPolicy: IfNotPresent
portainer:
  # Logo URL
  logo: ""
  # Enables Edge Compute Features
  edge_compute: false
  # Sets Snapshot interval
  snapshot_interval: 5m
  hide_labels:
  # - label1=value1
  # - label2=value2
serviceAccount:
  main:
    enabled: true
    primary: true
rbac:
  main:
    enabled: true
    primary: true
    clusterWide: true
    rules:
      - apiGroups:
          - "*"
        resources:
          - "*"
        verbs:
          - "*"
service:
  main:
    ports:
      main:
        port: 10400
        protocol: https
        targetPort: 9443
  edge:
    enabled: true
    ports:
      edge:
        enabled: true
        port: 10401
        targetPort: 10401
persistence:
  data:
    enabled: true
    mountPath: "/data"
  cache:
    enabled: true
    mountPath: "/.cache"
    type: emptyDir
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      automountServiceAccountToken: true
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              port: 9443
              type: https
            readiness:
              port: 9443
              type: https
            startup:
              port: 9443
              type: https
updated: true
