image:
  repository: ghcr.io/elfhosted/zilean
  pullPolicy: IfNotPresent
  tag: v2.0.0@sha256:343e425e36814d431ae2720df6f9ced67a5ff48e791e5cca8c4c90c00e6f6900

service:
  main:
    ports:
      main:
        port: 8181
        targetPort: 8181

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/healthchecks/ping"
            readiness:
              path: "/healthchecks/ping"
            startup:
              path: "/healthchecks/ping"
          env:
            Zilean__Database__ConnectionString: '{{ printf "Host=%s;Port=5432;Database=%s;Username=%s;Password=%s" (.Values.cnpg.main.creds.host | trimAll "\"") .Values.cnpg.main.database .Values.cnpg.main.user .Values.cnpg.main.creds.password }}'

persistence:
  data:
    enabled: true
    mountPath: "/app/data"
    
cnpg:
  main:
    enabled: true
    user: zilean
    database: zilean

portal:
  open:
    enabled: true

