creation_rules:
  - path_regex: cluster.*\.secret.ya?ml
    encrypted_regex: "((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))"
    age: >-
      age10te85vgqaygcrrz6g24guk5flht2kjmlkfem0lj9ml7yly8f5acqzdgtga
  - path_regex: .*\.secret
    encrypted_regex: "((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))"
    age: >-
      age10te85vgqaygcrrz6g24guk5flht2kjmlkfem0lj9ml7yly8f5acqzdgtga
  - path_regex: age.agekey.enc
    age: >-
      age10te85vgqaygcrrz6g24guk5flht2kjmlkfem0lj9ml7yly8f5acqzdgtga
  - path_regex: talenv.yaml
    age: >-
      age10te85vgqaygcrrz6g24guk5flht2kjmlkfem0lj9ml7yly8f5acqzdgtga
  - path_regex: talsecret.yaml
    encrypted_regex: "((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))"
    age: >-
      age10te85vgqaygcrrz6g24guk5flht2kjmlkfem0lj9ml7yly8f5acqzdgtga
