image:
  repository: jesec/flood
  pullPolicy: IfNotPresent
  tag: 4.8.4@sha256:3b80bb2d6764045981d87c5add0ce64c59e87fe84d2feb3bd343d2cbff28acf0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FLOOD_OPTION_RUNDIR: /data
service:
  main:
    ports:
      main:
        port: 10036
        targetPort: 3000
persistence:
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
