image:
  repository: jvmilazz0/kavita
  pullPolicy: IfNotPresent
  tag: 0.8.3@sha256:6d6bf8e9be270637d6741d5204d8a18c4def8fea8cbefe7215c898e470e5ca92
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 5000
        port: 10189
persistence:
  config:
    enabled: true
    mountPath: "/kavita/config"
  manga:
    enabled: true
    mountPath: "/manga"
  tmp:
    enabled: false
portal:
  open:
    enabled: true
