image:
  pullPolicy: IfNotPresent
  repository: ich777/krusader
  tag: latest@sha256:0948b3aac126de4d7c7dae40680b7f4a8cf7bb3728bd27c0a0c41af4b5091cd6
persistence:
  containerpath:
    enabled: true
    mountPath: /krusader
  datapath:
    enabled: true
    mountPath: /mnt/user
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8080
        protocol: tcp
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CUSTOM_RES_H: "768"
            CUSTOM_RES_W: "1280"
            NOVNC_RESIZE: remote
            RUNASROOT: "false"
            USER_LOCALES: en_US.UTF-8 UTF-8
