name: Publish Wiki via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
        with:
          ref: "master"
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
