image:
  repository: ghcr.io/ix-ai/smtp
  pullPolicy: IfNotPresent
  tag: v0.5.6@sha256:2e668f4b254865c8c02a8ccfcf88b4b2d65a96fbcc4e1b45ca7e83ca26acc9fc

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        port: 25

smtprelay:
  networks:
    - 172.16.0.0/16
  domains: []
  generic:
    address: ""
    port: 587
    user: ""
    pass: ""
    aliases: []

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            PORT: "{{ .Values.service.main.ports.main.port }}"
            RELAY_NETWORKS: '{{ join " : " .Values.smtprelay.networks }}'
            RELAY_DOMAINS: '{{ join " : " .Values.smtprelay.domains }}'
            DISABLE_IPV6: true
            # # Generic SMTP Relay
            SMARTHOST_ADDRESS: "{{ .Values.smtprelay.generic.address }}"
            SMARTHOST_PORT: "{{ .Values.smtprelay.generic.port }}"
            SMARTHOST_USER: "{{ .Values.smtprelay.generic.user }}"
            SMARTHOST_PASSWORD: "{{ .Values.smtprelay.generic.pass }}"
            SMARTHOST_ALIASES: '{{ join " : " .Values.smtprelay.generic.aliases }}'

portal:
  open:
    enabled: false
