image:
  repository: traggo/server
  pullPolicy: IfNotPresent
  tag: 0.5.0@sha256:db747dd56af7fb8cd8f4bedeebfe804f69d29f12fd583d13e18d9ebaf944a063
traggo:
  username: admin
  password: admin
  pass_strength: 10
  log_level: info
service:
  main:
    ports:
      main:
        protocol: http
        port: 12117
persistence:
  config:
    enabled: true
    mountPath: /opt/traggo/data
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: http
          envFrom:
            - secretRef:
                name: "secret"
