image:
  repository: ghcr.io/linkwarden/linkwarden
  pullPolicy: IfNotPresent
  tag: v2.7.1@sha256:d7e76ab5cd00e53f07c8a78b5e6aff0341a8f9a3e1c2d35177d02c2aad8ca8fb

config:
  nextauth_url: "http://example.com"
  pagination_take_count: 20
  autoscroll_timeout: 30
  disable_registration: false
  archive_limit: 5

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        port: 2985
        targetPort: 3000

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: std
            NEXTAUTH_SECRET:
              secretKeyRef:
                name: linkwarden-secrets
                key: NEXTAUTH_SECRET
            NEXTAUTH_URL: "{{ .Values.config.nextauth_url }}"
            PAGINATION_TAKE_COUNT: "{{ .Values.config.pagination_take_count }}"
            STORAGE_FOLDER: "data"
            AUTOSCROLL_TIMEOUT: "{{ .Values.config.autoscroll_timeout }}"
            NEXT_PUBLIC_DISABLE_REGISTRATION: "{{ .Values.config.disable_registration }}"
            RE_ARCHIVE_LIMIT: "{{ .Values.config.archive_limit }}"

persistence:
  data:
    enabled: true
    mountPath: "/data/data"

cnpg:
  main:
    enabled: true
    database: linkwarden
    user: linkwarden

portal:
  open:
    enabled: true
