image:
  repository: shokoanime/server
  pullPolicy: IfNotPresent
  tag: v5.0.0@sha256:da43fd25a193eb97cae435a1d8a244d54c56b21bb3cabbce079fe2c39cfb064a
service:
  main:
    ports:
      main:
        port: 8111
        protocol: http
        targetPort: 8111
persistence:
  appdata:
    enabled: true
    mountPath: /home/shoko/.shoko/
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
