---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: metallb-config
    repo: oci://tccr.io/truecharts
    version: 5.1.13
    releaseName: metallb-config
    namespace: metallb-config
    valuesFile: values.yaml
commonAnnotations:
  meta.helm.sh/release-name: metallb-config
  meta.helm.sh/release-namespace: metallb-config
commonLabels:
  app.kubernetes.io/managed-by: Helm
