image:
  pullPolicy: IfNotPresent
  repository: accetto/ubuntu-vnc-xfce-chromium-g3
  tag: latest@sha256:9c2fcf5f921a2f1c6c4426d54db3e968166c9de6c457b12c875bdd6d1063d38f
persistence:
  internalshare:
    enabled: true
    mountPath: /UNRAID_SHARE
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 6901
        protocol: http
        targetPort: 6901
  webuivnc:
    enabled: true
    ports:
      webuivnc:
        enabled: true
        port: 5901
        protocol: tcp
        targetPort: 5901
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            VNC_PW: unraid
            VNC_RESOLUTION: 1360x768
