image:
  repository: ghcr.io/linuxserver/filezilla
  tag: 3.67.0@sha256:b1e0e0b61a608a46dd1f1ae2ed98743ca07b7ee10af06354cbf35fc1c467c4dd
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          securityContext:

service:
  main:
    ports:
      main:
        port: 10035
        protocol: http
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: false

portal:
  open:
    enabled: true
