image:
  repository: ghcr.io/tasmoadmin/tasmoadmin
  tag: v4.1.3@sha256:5737d0d5deb9f0d62a88eac7ae0d03ad0bda9a00ae57cd6a8b77b82e562381b1
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            TASMO_DEBUG: 1

service:
  main:
    ports:
      main:
        port: 9541
        protocol: http
        targetPort: 80

persistence:
  data:
    enabled: true
    mountPath: /data

portal:
  open:
    enabled: true
