image:
  repository: benbusby/whoogle-search
  tag: 0.9.0@sha256:2c87cc33ebbd1091f34e3dddd0a4e016ad1680d840945a80f4f410b4354779aa
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10052
        targetPort: 5000
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            WHOOGLE_CONFIG_COUNTRY: ""
            WHOOGLE_CONFIG_THEME: "dark"
            WHOOGLE_CONFIG_SAFE: true
            WHOOGLE_CONFIG_ALTS: false
            WHOOGLE_CONFIG_TOR: false
            WHOOGLE_CONFIG_NEW_TAB: false
            WHOOGLE_CONFIG_GET_ONLY: false
            WHOOGLE_CONFIG_URL: https://<your url>/
            WHOOGLE_CONFIG_STYLE: ""
