image:
  pullPolicy: IfNotPresent
  repository: ich777/openttdserver
  tag: latest@sha256:259924c45cb21e1dcb0f59c4b3d755db7e06e048159465d66cb215b3eabf8cdd
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 9015
        protocol: http
        targetPort: 8080
  tcpgameport:
    enabled: true
    ports:
      tcpgameport:
        enabled: true
        port: 3979
        protocol: tcp
        targetPort: 3979
  udpgameport:
    enabled: true
    ports:
      udpgameport:
        enabled: true
        port: 3979
        protocol: udp
        targetPort: 3979
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_PARAMS: ""
            GAME_VERSION: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
            GFX_PK_V: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
