image:
  repository: ghcr.io/linuxserver/pylon
  pullPolicy: IfNotPresent
  tag: 2.10.0@sha256:e4a097f387f1a7c6709dacf1c06e781e811601ad1c21a81d592333b432f002c0
service:
  main:
    ports:
      main:
        targetPort: 3131
        port: 3131
persistence:
  code:
    enabled: true
    mountPath: "/code"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GITURL: ""
            PYUSER: ""
            PYPASS: ""
