image:
  pullPolicy: IfNotPresent
  repository: ich777/debian-mirror
  tag: latest@sha256:3c78d255c729e2db8c66445261237527a1628f927c26cc40fb915f7b5e1a6d9b
persistence:
  config:
    enabled: true
    mountPath: /debian-mirror/config
  data:
    enabled: true
    mountPath: /debian-mirror/data
  base:
    enabled: true
    mountPath: /debian-mirror
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 980
        protocol: tcp
        targetPort: 980
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATA_DIR: "/debian-mirror"
            CONFIG_DIR: "/debian-mirror/config"
            MIRROR_DIR: "/debian-mirror/data"
            APACHE2_PORT: "980"
            CRON_SCHEDULE: "0 1 * * *"
            FORCE_UPDATE: "false"
            DATA_PERM: "770"
