image:
  repository: ghcr.io/manyfold3d/manyfold
  tag: 0.81.0@sha256:9c5c3d19b6cde7e33ba64a06c8dcf662492687c13dea9a0d5a6b5df49441db1e
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 3214
        port: 3214

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATABASE_ADAPTER: postgresql
            DATABASE_HOST: "{{ .Values.cnpg.main.creds.host }}"
            DATABASE_NAME: "{{ .Values.cnpg.main.database }}"
            DATABASE_USER: "{{ .Values.cnpg.main.user }}"
            DATABASE_PASSWORD:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            SECRET_KEY_BASE:
              secretKeyRef:
                name: manyfold-secrets
                key: SECRET_KEY_BASE
            REDIS_URL:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: url
          probes:
            readiness:
              enabled: true
              type: http
              path: /health
            liveness:
              enabled: true
              type: http
              path: /health
            startup:
              enabled: true
              type: http
              path: /health

persistence:
  libraries:
    enabled: true
    mountPath: "/libraries"

cnpg:
  main:
    enabled: true
    user: manyfold
    database: manyfold

redis:
  enabled: true

portal:
  open:
    enabled: true
