image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: pvkii@sha256:7793376795444a883ebb8d5abeb19fd51f4fd13cdcd74deebe034d55d767c2ac
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 27015
        protocol: udp
        targetPort: 27015
  tcprcon:
    enabled: true
    ports:
      tcprcon:
        enabled: true
        port: 27015
        protocol: tcp
        targetPort: 27015
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATA_PERM: "770"
            GAME_ID: "17575"
            GAME_NAME: pvkii
            GAME_PARAMS: -maxplayers 18 +map bt_island
            GAME_PORT: "27015"
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
          probes:
            liveness:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
              type: tcp
            readiness:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
              type: tcp
            startup:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
              type: tcp
