image:
  repository: haveagitgat/tdarr
  pullPolicy: IfNotPresent
  tag: 2.26.01@sha256:a4a42a12022794fb7cd21fa173695aadcd17510274449c159d5fef44da3b6a1d
service:
  main:
    ports:
      main:
        port: 8265
  comm:
    enabled: true
    ports:
      comm:
        enabled: true
        port: 8266
persistence:
  configs:
    enabled: true
    mountPath: "/app/configs"
  server:
    enabled: true
    mountPath: "/app/server"
  logs:
    enabled: true
    mountPath: "/app/logs"
  transcode-cache:
    enabled: true
    mountPath: "/temp"
  media:
    enabled: true
    mountPath: "/media"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            webUIPort: "{{ .Values.service.main.ports.main.port }}"
            serverPort: "{{ .Values.service.comm.ports.comm.port }}"
            # User Defined
            internalNode: true
            serverIP: "127.0.0.1"
            nodeID: "Internal Node"
