image:
  repository: ghcr.io/anotherstranger/borg-server
  pullPolicy: IfNotPresent
  tag: 2.6.4@sha256:2be29d917041621f22857c5d1c9dc3665836ff74846cc6c5b2e9a8ab88f452de

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: tcp
        targetPort: 22
        port: 8022

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BORG_UID: "{{ .Values.securityContext.container.PUID }}"
            BORG_GID: "{{ .Values.securityContext.pod.fsGroup }}"
          securityContext:
            capabilities:
              add:
                - SYS_CHROOT
                - KILL

persistence:
  borg:
    enabled: true
    mountPath: "/var/lib/docker-borg"
  backups:
    enabled: true
    mountPath: "/home/borg/backups"
  ssh:
    enabled: true
    mountPath: "/home/borg/.ssh"

portal:
  open:
    enabled: false
