image:
  repository: xhofe/alist-aria2
  pullPolicy: IfNotPresent
  tag: v3.38.0@sha256:f5dba0ff984ef218284334f073b3d97a6c56919de2bd02b1d8127e5313282197
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 5244
        protocol: http
        port: 10167
  aria2:
    enabled: true
    ports:
      aria2:
        enabled: true
        targetPort: 6800
        protocol: http
        port: 6800
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
persistence:
  data:
    enabled: true
    mountPath: /opt/alist/data
portal:
  open:
    enabled: true
