image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/sethforprivacy/simple-monerod
  tag: v0.18.3.4@sha256:a2209695f5a4635220703c89b5575bf095d87cc999482df18b6bf78dd2d58557

monero:
  rpcbindip: "0.0.0.0"
  rpcbindport: "18089"
  publicnode: true
  noigd: true
  enablednsblocklist: true
  pruneblockchain: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        port: 18080
        protocol: tcp
        targetPort: 18080
  rpc:
    enabled: true
    ports:
      rpc:
        enabled: true
        port: 18089
        protocol: tcp
        targetPort: 18089

persistence:
  blockchainstorage:
    enabled: true
    mountPath: /home/monero/.bitmonero

portal:
  open:
    enabled: true
