image:
  repository: pepperlabs/peppermint
  pullPolicy: IfNotPresent
  tag: latest@sha256:e029b4c57909b35c7c5b6d2eacc58e60942ad03b3bad196ccf5ecb3195fbc016

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 3000
        port: 10699
  api:
    enabled: true
    type: ClusterIP
    ports:
      api:
        enabled: true
        protocol: http
        port: 5003

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DB_USERNAME: "{{ .Values.cnpg.main.user }}"
            DB_PASSWORD:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            DB_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
            SECRET:
              secretKeyRef:
                name: peppermint-secrets
                key: SECRET
            API_URL: '{{ printf "http://%v:%v" (include "tc.v1.common.lib.chart.names.fullname" $) .Values.service.api.ports.api.port }}'

cnpg:
  main:
    enabled: true
    user: peppermint
    database: peppermint

portal:
  open:
    enabled: true
