image:
  repository: yourselfhosted/slash
  pullPolicy: IfNotPresent
  tag: 1.0.0@sha256:4d1ca12f0c5e1701cf8d7140f25bd247bdad4ab5711432e06b4c8cc8993b76ea
service:
  main:
    ports:
      main:
        protocol: http
        port: 5231
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SLASH_PORT: "{{ .Values.service.main.ports.main.port }}"
persistence:
  config:
    enabled: true
    mountPath: "/var/opt/slash"
portal:
  open:
    enabled: true
