image:
  repository: louislam/uptime-kuma
  pullPolicy: IfNotPresent
  tag: 1.23.15-debian@sha256:d8b1b2151256bda3a99e822902fcbeb27b3eca6ef6d93fad25d2062b9fb61ad2
security:
  PUID: 0
service:
  main:
    ports:
      main:
        port: 3001
persistence:
  config:
    enabled: true
    mountPath: "/app/data"
portal:
  open:
    enabled: true
metrics:
  main:
    enabled: true
    type: "servicemonitor"
    endpoints:
      - port: main
        path: /metrics
    prometheusRule:
      enabled: false
securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            UPTIME_KUMA_PORT: "{{ .Values.service.main.ports.main.port }}"
