image:
  repository: ronivay/xen-orchestra
  tag: 5.157.1@sha256:134d199de4598df8a8311f3784a0ba07bf925132c945205c3cd83a6f01d23292
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        protocol: https
        port: 10324
persistence:
  xo-data:
    enabled: true
    mountPath: "/var/lib/xo-server"
  redis-data:
    enabled: true
    mountPath: "/var/lib/redis"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    capabilities:
      add:
        - SYS_ADMIN
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              type: exec
              command:
                - /healthcheck.sh
            readiness:
              enabled: true
              type: exec
              command:
                - /healthcheck.sh
            startup:
              enabled: true
              type: exec
              command:
                - /healthcheck.sh
          env:
            HTTPS_PORT: "{{ .Values.service.main.ports.main.port }}"
            # Just so it doesn't try to bind port 80
            HTTP_PORT: "{{ add1 .Values.service.main.ports.main.port }}"
            REDIRECT_TO_HTTPS: true
