image:
  repository: gotson/komga
  tag: 1.14.1@sha256:6e9336c7790c8481afa767e6f39395b720746f5f86ce733547c58799016adf8e
  pullPolicy: IfNotPresent
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
          probes:
            liveness:
              port: "{{ .Values.service.main.ports.main.port }}"
              path: /actuator/health
            readiness:
              port: "{{ .Values.service.main.ports.main.port }}"
              path: /actuator/health
            startup:
              type: tcp
              port: "{{ .Values.service.main.ports.main.port }}"
service:
  main:
    ports:
      main:
        port: 10085
persistence:
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: true
