image:
  repository: ghcr.io/linuxserver/znc
  pullPolicy: IfNotPresent
  tag: 1.9.1@sha256:5f8d11cb9d26942ee428331137a0e0ff596d68154d589e25ea3c37c35e192022
service:
  main:
    ports:
      main:
        targetPort: 6501
        port: 6501
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
