image:
  repository: requarks/wiki
  tag: 2.5.305@sha256:707fa8f0c739d098346eff46af4ef3e71f10df88b0b49785c70b4cf0075274d5
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10045
        targetPort: 3000
cnpg:
  main:
    enabled: true
    user: wikijs
    database: wikijs
# /wiki/data is a temporary dir. Without mounting as emptyDir it's only writable by root.
# https://docs.requarks.io/en/install/config#data-paths
persistence:
  wikicache:
    enabled: true
    mountPath: "/wiki/data/"
    type: emptyDir
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/healthz"
            readiness:
              path: "/healthz"
            startup:
              path: "/healthz"
          env:
            DB_TYPE: "postgres"
            DB_NAME: "{{ .Values.cnpg.main.database }}"
            DB_USER: "{{ .Values.cnpg.main.user }}"
            DB_PORT: "5432"
            DB_PASS:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            DB_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
