image:
  pullPolicy: IfNotPresent
  repository: ich777/urbanterror
  tag: latest@sha256:c18a8a5051b5b77ea5cdfead78483ddae46b2bb1744776c6b83cf388e9f761dd
persistence:
  datadir:
    enabled: true
    mountPath: /urbanterror
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 27960
        protocol: udp
        targetPort: 27960
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CHECK_FOR_UPDATES: "true"
            START_PARAMS: ""
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
