image:
  repository: docuseal/docuseal
  tag: 1.7.6@sha256:632f6ed179fdd97af683f04c03c128278720209da1b298c292e0126558a22a01
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10310
        protocol: http
        targetPort: 3000

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: std
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /

persistence:
  data:
    enabled: true
    mountPath: /data

portal:
  open:
    enabled: true

cnpg:
  main:
    enabled: true
    user: docuseal
    database: docuseal
