image:
  repository: itzg/minecraft-server
  tag: 2024.10.1@sha256:85a2c2df862c593fbe24d6078e5074612f694a9a3bfa3d5624a01b69387be0da
  pullPolicy: Always
j21Image:
  repository: itzg/minecraft-server
  tag: 2024.10.1-java21@sha256:85a2c2df862c593fbe24d6078e5074612f694a9a3bfa3d5624a01b69387be0da
  pullPolicy: Always
j21graalvmImage:
  repository: itzg/minecraft-server
  tag: 2024.10.1-java21-graalvm@sha256:734c2b760e1499a8f390ee695419a542050325254a073de6c6de81325cfdcf39
  pullPolicy: Always
j21alpineImage:
  repository: itzg/minecraft-server
  tag: 2024.10.1-java21-alpine@sha256:ad1d082be9465fc411a84453402fdb05a9c17dbf1d56d391dca8f4e7f819e586
  pullPolicy: Always
j17Image:
  repository: itzg/minecraft-server
  tag: 2024.10.1-java17@sha256:ee928123677e7c11b3eac2eff74f4021bd538de2752640c00bca65a0b99f5790
  pullPolicy: Always
j17jdkImage:
  repository: itzg/minecraft-server
  tag: 2024.6.1-java17-jdk@sha256:2c43fcede436aff9f50b1adf4448d55d221651be471ef41412232c141bfa89f6
  pullPolicy: Always
j17graalvmImage:
  repository: itzg/minecraft-server
  tag: 2024.10.1-java17-graalvm@sha256:c782346b70fdaba64369bd7ee363109d23e9efd71a389a05eab20e3c7c664395
  pullPolicy: Always
j17alpineImage:
  repository: itzg/minecraft-server
  tag: 2024.10.1-java17-alpine@sha256:36da1fadbd791347e5fa60c0939ebc4eedf5386dc96493efe7bc4c651e05c946
  pullPolicy: Always
j11Image:
  repository: itzg/minecraft-server
  tag: 2024.10.1-java11@sha256:8f59c748e47b49c5d05e5761ecbe9733afe63296e0ba0ce42d7c4e4542aee75c
  pullPolicy: Always
j8Image:
  repository: itzg/minecraft-server
  tag: 2024.10.1-java8@sha256:98f4c77a3452b0ea4fe9abc8acb1078f8c0d4e45de048f02d88d6a9255318c73
  pullPolicy: Always
j8graalvmImage:
  repository: itzg/minecraft-server
  tag: 2024.10.1-java8-graalvm-ce@sha256:f1dc38672e70a4ed2cf738a0cccce7246b11f50f28154eac06afca9d086cb35f
  pullPolicy: Always
j8jdkImage:
  repository: itzg/minecraft-server
  tag: 2024.10.1-java8-jdk@sha256:32f5ecc8b086d8ed8fb48f0b66f9ed26d463634baf88b6d090370a3909431321
  pullPolicy: Always
j8alpineImage:
  repository: itzg/minecraft-server
  tag: 2024.9.0-java8-alpine@sha256:ee8505b9670a82b7703ec35b2a87fe9b7f7823b50ae50fad18bf1fe511e577f9
  pullPolicy: Always
mcBackupImage:
  repository: itzg/mc-backup
  tag: latest@sha256:b40aebf4f089b373495c92483c7990222560977b5e703de507733401b38456f8
  pullPolicy: Always

service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        protocol: tcp
        port: 25565
      query:
        enabled: true
        protocol: udp
        port: 25565
  rcon:
    enabled: true
    ports:
      rcon:
        enabled: true
        port: 25575

mcbackup:
  zstd_params:
    - --long=25
    - --single-thread
  # comma separated list
  excludes:
    - "*.jar"
    - "cache"
    - "logs"
    - "*.tmp"

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              enabled: true
              type: exec
              command:
                - mc-health
            readiness:
              enabled: true
              type: exec
              command:
                - mc-health
            startup:
              enabled: true
              type: exec
              command:
                - mc-health
          env:
            SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
            QUERY_PORT: "{{ .Values.service.main.ports.query.port }}"
            RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
            ENABLE_QUERY: "true"
            EULA: "TRUE"
            GUI: "FALSE"
            OVERRIDE_SERVER_PROPERTIES: true
            VERSION: "LATEST"
            TYPE: "VANILLA"
            DIFFICULTY: easy
            MAX_PLAYERS: 20
            MAX_WORLD_SIZE: 10000
            ALLOW_NETHER: true
            ANNOUNCE_PLAYER_ACHIEVEMENTS: true
            ENABLE_COMMAND_BLOCK: false
            FORCE_GAMEMODE: false
            GENERATE_STRUCTURES: true
            HARDCORE: false
            MAX_BUILD_HEIGHT: 256
            MAX_TICK_TIME: 60000
            SPAWN_ANIMALS: true
            SPAWN_MONSTERS: true
            SPAWN_NPCS: true
            VIEW_DISTANCE: 16
            MODE: survival
            MOTD: "Welcome to Minecraft on TrueNAS Scale!"
            PVP: false
            LEVEL_TYPE: DEFAULT
            LEVEL: world
            ONLINE_MODE: true
            MEMORY: 2048M
            RCON_PASSWORD: "secretrconpass"
            # PACKWIZ_URL: ""
            # CUSTOM_SERVER: ""
            # QUILT_LOADER_VERSION: ""
            # QUILT_LAUNCHER: ""
            # QUILT_LAUNCHER_URL: ""
            # PUFFERFISH_BUILD: "lastSuccessfulBuild"
            # FORGEVERSION: ""
            # FORGE_INSTALLER: ""
            # FORGE_INSTALLER_URL: ""
            # FABRIC_LOADER_VERSION: ""
            # FABRIC_INSTALLER: ""
            # FABRIC_INSTALLER_URL: ""
            # SPIGOT_DOWNLOAD_URL: ""
            # BUILD_FROM_SOURCE: false
            # BUKKIT_DOWNLOAD_URL: ""
            # PAPERBUILD: ""
            # PAPER_DOWNLOAD_URL: ""
            # AIRPLANE_BUILD: "lastSuccessfulBuild"
            # MAGMA_CHANNEL: "stable"
            # MOHIST_BUILD: ""
            # CANYON_BUILD: ""
            # SPONGEBRANCH: "STABLE"
            # SPONGEVERSION: ""
            # LIMBO_BUILD: "LATEST"
            # LIMBO_SCHEMA_FILENAME: "default.schem"
            # CRUCIBLE_RELEASE: "latest"
            # FTB_MODPACK_ID: ""
            # FTB_MODPACK_VERSION_ID: ""
            # CF_SERVER_MOD: ""
            # CF_BASE_DIR: ""
            # USE_MODPACK_START_SCRIPT: true
            # FTB_LEGACYJAVAFIXER: false
            # WHITELIST: ""
            # OPS: ""
            # ICON: ""
            # SEED: ""
            # GENERATOR_SETTINGS: ""
            # WORLD: ""
            # FORCE_REDOWNLOAD: false
            # USE_FLARE_FLAGS: false
            # USE_AIKAR_FLAGS: true
            # USE_SIMD_FLAGS: false
            # JVM_OPTS: ""
            # JVM_XX_OPTS: ""
            # CF_API_KEY
            # CF_PAGE_URL
            # CF_SLUG
            # CF_EXCLUDE_INCLUDE_FILE
            # CF_EXCLUDE_MODS
            # CF_FORCE_INCLUDE_MODS
            # CF_FORCE_SYNCHRONIZE
            # CF_OVERRIDES_SKIP_EXISTING
            # CF_PARALLEL_DOWNLOADS
            # CF_SET_LEVEL_FROM
        mcbackup:
          enabled: true
          imageSelector: mcBackupImage
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            BACKUP_METHOD: "tar"
            DEST_DIR: "{{.Values.persistence.backups.mountPath }}"
            SRC_DIR: "{{.Values.persistence.data.mountPath }}"
            SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
            RCON_HOST: '{{ printf "%s-rcon" (include "tc.v1.common.lib.chart.names.fullname" $) }}'
            RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
            RCON_PASSWORD: "{{ .Values.workload.main.podSpec.containers.main.env.RCON_PASSWORD }}"
            SERVER_HOST: '{{ include "tc.v1.common.lib.chart.names.fullname" $ }}'

            ZSTD_PARAMETERS: '{{ join " " .Values.mcbackup.zstd_params }}'
            EXCLUDES: '{{ join "," .Values.mcbackup.excludes }}'

            INITIAL_DELAY: "2m"
            BACKUP_INTERVAL: "24h"
            PRUNE_BACKUPS_DAYS: "7"
            PAUSE_IF_NO_PLAYERS: "false"
            PLAYERS_ONLINE_CHECK_INTERVAL: "5m"
            LINK_LATEST: "false"
            TAR_COMPRESS_METHOD: "zstd"

persistence:
  data:
    enabled: true
    targetSelector:
      main:
        main:
          mountPath: /data
        mcbackup:
          mountPath: /data
          readOnly: true
  backups:
    enabled: true
    targetSelector:
      main:
        mcbackup:
          mountPath: /backups

portal:
  open:
    enabled: false
