image:
  pullPolicy: IfNotPresent
  repository: chronograf
  tag: latest@sha256:577141d452b5a3cccbd1db19145202a297d49c663bb79bbf779a8f34c6408f44
persistence:
  chronograf:
    enabled: true
    mountPath: /var/lib/chronograf
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8888
        protocol: tcp
        targetPort: 8888
