---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: kubeapps
    repo: https://charts.truecharts.org
    version: 0.0.1
    releaseName: kubeapps
    namespace: kubeapps
commonAnnotations:
  meta.helm.sh/release-name: kubeapps
  meta.helm.sh/release-namespace: kubeapps
commonLabels:
  app.kubernetes.io/managed-by: Helm
