image:
  repository: anonaddy/anonaddy
  tag: 1.2.3@sha256:21164e3e3b3f23adf74a436901727728f7f1d1e6d57d2e2e59754f7f9f381a46
  pullPolicy: IfNotPresent
strategy:
  type: Recreate
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10110
        targetPort: 8000
  smtp:
    enabled: true
    ports:
      smtp:
        enabled: true
        port: 25
        targetPort: 25
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            ANONADDY_DOMAIN: "chart-example.local"
            APP_URL: "http://localhost:10110"
            # The from name to be used for outgoing email notifications from AnonAddy
            MAIL_FROM_NAME: Example
            # The from address to be used for outgoing email notifications from AnonAddy
            MAIL_FROM_ADDRESS: mailer@example.com
            # just smtp is configurable
            MAIL_DRIVER: smtp
            MAIL_HOST: mail.example.com
            MAIL_PORT: 25
            MAIL_ENCRYPTION: tls
            MAIL_EHLO_DOMAIN: mail.example.com
            MAIL_VERIFY_PEER: false
            DB_DATABASE: "{{ .Values.mariadb.mariadbDatabase }}"
            DB_USERNAME: "{{ .Values.mariadb.mariadbUsername }}"
            DB_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: plainhost
            DB_PASSWORD: "{{ .Values.mariadb.password }}"
            REDIS_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: plainhost
            REDIS_PASSWORD: "{{ .Values.redis.password }}"
            APP_KEY:
              secretKeyRef:
                name: anonaddy-secrets
                key: APP_KEY
            ANONADDY_SECRET:
              secretKeyRef:
                name: anonaddy-secrets
                key: ANONADDY_SECRET
persistence:
  config:
    enabled: true
    mountPath: /config
redis:
  enabled: true
  includeCommon: true
mariadb:
  enabled: true
  includeCommon: true
  mariadbUsername: anonaddy
  mariadbDatabase: anonaddy
portal:
  open:
    enabled: true
