name: CI

on: [push]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    container:
      image: ixsystems/catalog_validation:latest@sha256:ec054455af9857782d13f0507b0e0378ed0dee83dab11a3e1e5939eebb083522

    steps:
      - name: Checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1

      - name: Build deb package
        run: >
          dpkg-buildpackage
          -B
          --no-sign
          -jauto

      - name: Create artifacts dir
        run: mkdir artifacts
        if: success()

      - name: Move artifacts
        run: mv ../*.deb artifacts
        if: success()

      - uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5 # v1
        with:
          name: py-catalog-validation
          path: artifacts
        if: success()
