image:
  pullPolicy: IfNotPresent
  repository: ofawx/bitcoind
  tag: latest@sha256:f67e80a247759f01d0610b28ea58f35ce841ad036819f561cca473cf4c6155d2
persistence:
  data:
    enabled: true
    mountPath: /root/.bitcoin/
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  localrpc:
    enabled: true
    ports:
      localrpc:
        enabled: true
        port: 8332
        protocol: tcp
        targetPort: 8332
  main:
    ports:
      main:
        port: 8333
        protocol: tcp
        targetPort: 8333
