---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: openebs
    repo: oci://tccr.io/truecharts
    version: 2.1.15
    releaseName: openebs
    namespace: openebs
commonAnnotations:
  meta.helm.sh/release-name: openebs
  meta.helm.sh/release-namespace: openebs
commonLabels:
  app.kubernetes.io/managed-by: Helm
