image:
  repository: misskey/misskey
  pullPolicy: IfNotPresent
  tag: 2024.10.1@sha256:68274bd20952701a4fbc8d6488b260bae45a4db6187e4fb2a1e6c8480e067190

securityContext:
  pod:
    fsgroup: 33
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 3003

misskey:
  # Final accessible URL seen by a user. ONCE YOU HAVE STARTED THE INSTANCE, DO NOT CHANGE THE URL SETTINGS AFTER THAT!
  url: "https://example.tld/"
  # ID generation method. 'aid' recommended.
  id: "aid"
  other:
    disableHSTS: false
    signToActivityPubGet: true
    maxFileSize: 262144000
    clusterLimit: 1
    deliverJobConcurrency: 128
    inboxJobConcurrency: 16
    relashionshipJobConcurrency: 16
    deliverJobPerSec: 128
    inboxJobPerSec: 16
    relashionshipJobPerSec: 64
    deliverJobMaxAttempts: 12
    inboxJobMaxAttempts: 8
    allowedPrivateNetworks:
      - 127.0.0.1/32
    proxyBypassHosts:
      - api.deepl.com
      - api-free.deepl.com
      - www.recaptcha.net
      - hcaptcha.com
      - challenges.cloudflare.com

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NODE_ENV: production

persistence:
  misskeyconfig:
    enabled: true
    type: configmap
    objectName: misskeyconfig
    mountPath: "/misskey/.config"
  files:
    enabled: true
    mountPath: "/misskey/files"

cnpg:
  main:
    enabled: true
    user: misskey
    database: misskey

redis:
  enabled: true
  includeCommon: true
  username: default

portal:
  open:
    enabled: true
