image:
  repository: ixsystems/truecommand
  pullPolicy: IfNotPresent
  tag: 3.0.2@sha256:d2d90dd617ee8b49a556d830762b7c5488bbaa3d574f28fccd9e79ff2ca76d01
service:
  main:
    ports:
      main:
        port: 10031
        targetPort: 80
persistence:
  data:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
