image:
  repository: ipfs/kubo
  pullPolicy: IfNotPresent
  tag: v0.30.0@sha256:6a8e6e0e926be6c6664fc6188d9fdd44dfcd5a77bc9c0d3e37d8b8dcc9c6c014
service:
  main:
    ports:
      main:
        port: 10125
        targetPort: 5001
  peer-tcp:
    enabled: true
    ports:
      peer-tcp:
        enabled: true
        targetPort: 4001
        port: 4001
  peer-udp:
    enabled: true
    ports:
      peer-udp:
        protocol: udp
        enabled: true
        targetPort: 4001
        port: 4001
  gateway:
    enabled: true
    type: ClusterIP
    ports:
      gateway:
        enabled: true
        targetPort: 8080
        port: 10147
persistence:
  data:
    enabled: true
    mountPath: "/data/ipfs"
  staging:
    enabled: true
    mountPath: "/export"
  ipfs:
    enabled: true
    mountPath: "/ipfs"
  ipns:
    enabled: true
    mountPath: "/ipns"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/webui"
            readiness:
              path: "/webui"
            startup:
              path: "/webui"
          env:
            IPFS_PROFILE: "server"
            IPFS_SWARM_KEY: ""
            IPFS_SWARM_KEY_FILE: ""
