image:
  pullPolicy: IfNotPresent
  repository: redislabs/redisinsight
  tag: 2.58.0@sha256:c3885a6b0fe11b7f33001c0586af0a82101f9a4ab83d5af55f1904f5fc642815
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 10579
redisinsight:
  log_level: info
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            RI_APP_PORT: "{{ .Values.service.main.ports.main.port }}"
            RI_FILES_LOGGER: /logs
            RI_LOG_LEVEL: "{{ .Values.redisinsight.log_level }}"
persistence:
  config:
    enabled: true
    mountPath: /data
  logs:
    enabled: true
    mountPath: /logs
portal:
  open:
    enabled: true
