words:
  - azurecr
  - certman
  - CHARTPLACEHOLDER
  - clustertool-dev
  - devcontainer
  - helmignore
  - keybase
  - koanf
  - lscr
  - Msgf
  - ocir
  - pubring
  - tccr
  - TRAINPLACEHOLDER
  - truecharts
  - unmarshalling
