---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-system-kubelet-csr-approver
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./cluster/kube-system/kubelet-csr-approver/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
