---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-system-cilium
  namespace: flux-system
spec:
  path: ./cluster/kube-system/cilium/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
