---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: spegel
      version: v0.0.27
      sourceRef:
        kind: HelmRepository
        name: spegel
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
      grafanaDashboard:
        enabled: true
      serviceMonitor:
        enabled: false
      spegel:
        containerdSock: /run/containerd/containerd.sock
        containerdRegistryConfigPath: /etc/cri/conf.d/hosts
        appendMirrors: true
        registries:
          - https://tccr.io
          - https://cgr.dev
          - https://docker.io
          - https://ghcr.io
          - https://quay.io
          - https://mcr.microsoft.com
          - https://public.ecr.aws
          - https://gcr.io
          - https://registry.k8s.io
          - https://k8s.gcr.io
          - https://lscr.io
      service:
        registry:
          hostPort: 29999
