---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: metallb
    repo: oci://tccr.io/truecharts
    version: 13.1.15
    releaseName: metallb
    namespace: metallb
commonAnnotations:
  meta.helm.sh/release-name: metallb
  meta.helm.sh/release-namespace: metallb
commonLabels:
  app.kubernetes.io/managed-by: Helm
