image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: garrysmod@sha256:d6f2b26769607545d1df50b35fd12fa7bd9bb289d7091d53071e896503942fab
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 27015
        protocol: udp
        targetPort: 27015
  tcprcon:
    enabled: true
    ports:
      tcprcon:
        enabled: true
        port: 27015
        protocol: tcp
        targetPort: 27015
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "4020"
            GAME_NAME: garrysmod
            GAME_PARAMS: -secure +maxplayers 12 +map gm_flatgrass
            GAME_PORT: "27015"
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
          probes:
            liveness:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
              type: tcp
            readiness:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
              type: tcp
            startup:
              port: "{{ .Values.service.tcprcon.ports.tcprcon.targetPort }}"
              type: tcp
