image:
  pullPolicy: IfNotPresent
  repository: f0rc3/gokapi
  tag: v1.9.2@sha256:734a6d4cd57a2dc9ed7f719d567d95e786c36b0ebc8d816378a5312bcff83030
persistence:
  config:
    enabled: true
    mountPath: /app/config
  data:
    enabled: true
    mountPath: /app/data
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 53842
        protocol: http
        targetPort: 53842
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GOKAPI_LENGTH_ID: "15"
            GOKAPI_MAX_FILESIZE: "102400"
            GOKAPI_MAX_MEMORY_UPLOAD: "20"
            GOKAPI_PASSWORD: changme
            GOKAPI_USERNAME: admin
