image:
  pullPolicy: IfNotPresent
  repository: ich777/steamcmd
  tag: longvinter@sha256:b499da59e4f62a0811dbbc504f17f74de9e19ec780bcf0c455737113c2ed7509
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 27016
        protocol: udp
        targetPort: 27016
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_PARAMS: ""
            GAME_PORT: "27016"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
