image:
  repository: ghcr.io/linuxserver/smokeping
  pullPolicy: IfNotPresent
  tag: 2.8.2@sha256:57d3e6899cf48c11a0006588c45a1d7b81264c915705e86615f97856b93214f3
strategy:
  type: Recreate
service:
  main:
    ports:
      main:
        port: 10030
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/data"
  varrun:
    enabled: false
portal:
  open:
    enabled: true
securityContext:
  container:
    capabilities:
      add:
        - NET_RAW
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
