image:
  pullPolicy: IfNotPresent
  repository: ich777/mindustry-server
  tag: latest@sha256:9358262ccc423848f32a9b980e3c1292510ad83cdb882852db09e2f300b57054
persistence:
  serverfiles:
    enabled: true
    mountPath: /mindustry
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 6567
        protocol: tcp
        targetPort: 6567
  udpgameport:
    enabled: true
    ports:
      udpgameport:
        enabled: true
        port: 6567
        protocol: udp
        targetPort: 6567
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_PARAMS: ""
            GAME_V: latest@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
            SRV_NAME: DockerMindustry
