image:
  repository: ghcr.io/linuxserver/bookstack
  pullPolicy: IfNotPresent
  tag: 24.10.20241014@sha256:8bbb64561cc0fc311b7a9d6e02f8801535e3fa7d6764b03b53ff61caadd04fa6
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10112
        protocol: http
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DB_USERNAME: "{{ .Values.mariadb.mariadbUsername }}"
            DB_DATABASE: "{{ .Values.mariadb.mariadbDatabase }}"
            APP_URL: ""
            DB_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: plainhost
            DB_PASSWORD: "{{ .Values.mariadb.password }}"
            APP_KEY:
              secretKeyRef:
                name: secrets
                key: APP_KEY
persistence:
  config:
    enabled: true
    mountPath: /config
mariadb:
  enabled: true
  includeCommon: true
  mariadbUsername: bookstack
  mariadbDatabase: bookstack
portal:
  open:
    enabled: true
