image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/hotio/duplicacy
  tag: release-1.7.2@sha256:fe19c81113fe2996d21af387f12201dcd667204f9f812ddafeafe90874ee6706
securityContext:
  container:
    runAsGroup: 0
    runAsUser: 0
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        port: 3875
        protocol: http
        targetPort: 3875
persistence:
  config:
    enabled: true
    mountPath: /config
  cache:
    enabled: true
    mountPath: /cache
  logs:
    enabled: true
    mountPath: /logs
portal:
  open:
    enabled: true
