image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/jens-maus/raspberrymatic
  tag: latest@sha256:88c91a968ce6f19e9e44fbbf52e7643cf7adb1468ce2f44f4048b33d07bf1ea3
persistence:
  config:
    enabled: true
    mountPath: /usr/local
  control:
    enabled: true
    hostPath: /run/udev/control
    mountPath: /run/udev/control
    type: hostPath
  modules:
    enabled: true
    hostPath: /lib/modules
    mountPath: /lib/modules
    readOnly: true
    type: hostPath
  sys:
    enabled: true
    hostPath: /sys
    mountPath: /sys
    type: hostPath
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  ccu:
    enabled: true
    ports:
      ccu1:
        enabled: true
        port: 2001
        targetPort: 2001
      ccu2:
        enabled: true
        port: 2010
        targetPort: 2010
      ccu3:
        enabled: true
        port: 9292
        targetPort: 9292
      ccu4:
        enabled: true
        port: 8181
        targetPort: 8181
  main:
    ports:
      main:
        port: 10581
        protocol: http
        targetPort: 80
