image:
  repository: registry
  pullPolicy: IfNotPresent
  tag: 2@sha256:ac0192b549007e22998eb74e8d8488dcfe70f1489520c3b144a6047ac5efbe90
service:
  main:
    ports:
      main:
        port: 10096
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
