image:
  repository: ghcr.io/linuxserver/minetest
  pullPolicy: IfNotPresent
  tag: 5.9.1@sha256:c934ebe493290c7581c96eba36d08b85ee77d8dde8af998432e715f831eaa484
service:
  main:
    ports:
      main:
        protocol: udp
        targetPort: 30000
        port: 30000
persistence:
  config:
    enabled: true
    mountPath: "/config/.minetest"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
