image:
  pullPolicy: IfNotPresent
  repository: teamspeak
  tag: 3.13.7@sha256:f23e251a1327cc2d766ee8f4c485670be7a3864390faaec447309c8a946cd53f
persistence:
  data:
    enabled: true
    mountPath: /var/ts3server
  config:
    enabled: true
    mountPath: /var/run/ts3server
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        primary: true
        enabled: true
        port: 10011
        targetPort: 10011
      query:
        enabled: true
        port: 10022
        targetPort: 10022
      voice:
        enabled: true
        port: 9987
        protocol: udp
        targetPort: 9987
      files:
        enabled: true
        port: 30033
        targetPort: 30033
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            TS3SERVER_LICENSE: accept
