image:
  pullPolicy: IfNotPresent
  repository: yacy/yacy_search_server
  tag: latest@sha256:41547bceb701514dc2d75ebd167516a7778bc33b04cbe992d01efe5a251a430d
persistence:
  appdata:
    enabled: true
    mountPath: /opt/yacy_search_server/DATA
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  https:
    enabled: true
    ports:
      https:
        enabled: true
        port: 8443
        protocol: tcp
        targetPort: 8443
  main:
    ports:
      main:
        port: 8090
        protocol: http
        targetPort: 8090
