image:
  repository: intel/intel-gpu-plugin
  pullPolicy: IfNotPresent
  tag: 0.31.0@sha256:0e9b1c383c2b6b2690a9a6143c1d613e5b809abb4c27f8a38dd0f2a29e176896

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

workload:
  main:
    podSpec:
      type: DaemonSet
      containers:
        main:
          args:
            - -shared-dev-num
            - "5"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false

portal:
  open:
    enabled: false

persistence:
  devfs:
    enabled: true
    type: device
    mountPath: /dev/dri
    hostPath: /dev/dri
    readOnly: true
  sysfs:
    enabled: true
    type: device
    mountPath: /sys/class/drm
    hostPath: /sys/class/drm
    readOnly: true
  kubeletsockets:
    enabled: true
    type: hostPath
    mountPath: /var/lib/kubelet/device-plugins
    hostPath: /var/lib/kubelet/device-plugins
