image:
  repository: ghcr.io/linuxserver/quassel-core
  pullPolicy: IfNotPresent
  tag: 0.14.0@sha256:0cdfdfd0a0f7ba5c2c64d7e412834e2e6fadd5b94df904e52d08c09549d2f6f5
service:
  main:
    ports:
      main:
        targetPort: 4242
        port: 4242
  ident:
    enabled: true
    ports:
      ident:
        enabled: true
        targetPort: 10113
        port: 10113
persistence:
  varrun:
    enabled: true
cnpg:
  main:
    enabled: true
    user: quassel-core
    database: quassel-core
portal:
  open:
    enabled: false
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            DB_BACKEND: "PostgreSQL"
            DB_PGSQL_USERNAME: "{{ .Values.cnpg.main.user }}"
            DB_PGSQL_DATABASE: "{{ .Values.cnpg.main.database }}"
            DB_PGSQL_PORT: 5432
            AUTH_AUTHENTICATOR: "Database"
            RUN_OPTS: "--config-from-environment"
            DB_PGSQL_PASSWORD:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            DB_PGSQL_HOSTNAME:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
