image:
  repository: anirdev/slink
  pullPolicy: IfNotPresent
  tag: v1.2.1@sha256:11e123869839fb54160ffaba8bc0b4c2c8d28cf29d693dacf47bdb8d876798c8
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ORIGIN: "{{ .Values.chartContext.appUrl }}"
            USER_APPROVAL_REQUIRED: true
            IMAGE_MAX_SIZE: "15M"
persistence:
  database:
    enabled: true
    mountPath: "/app/var/data"
  images:
    enabled: true
    mountPath: "/app/slink/images"
portal:
  open:
    enabled: true
ingress:
  main:
    required: true
