# Project Information
site_name: JailMan
site_description: "Project Documentation for JailManager"
site_author: "JailManager Team"
docs_dir: content/
site_url: "https://wiki2.jailmanager.org"

# Repository
repo_name: "jailmanager/jailman"
repo_url: "https://github.com/jailmanager/jailman"
edit_uri: "edit/content/"

theme:
  name: "material"
  features:
    - tabs
  language: "en"

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
