image:
  repository: ghcr.io/chroma-core/chroma
  pullPolicy: IfNotPresent
  tag: 0.5.15@sha256:7c44cf61eb3f210fa8641c6c943d5621b9626ce863d89247183ffde37717e576

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8000
        port: 10690

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/api/v1/heartbeat"
            readiness:
              path: "/api/v1/heartbeat"
            startup:
              path: "/api/v1/heartbeat"
          env:
            IS_PERSISTENT: true

persistence:
  config:
    enabled: true
    mountPath: "/chroma/chroma"

portal:
  open:
    enabled: true
